/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppEpicsEpicIdEditImport } from './routes/app/epics/$epicId/edit'

// Create/Update Routes

const AppEpicsEpicIdEditRoute = AppEpicsEpicIdEditImport.update({
  id: '/app/epics/$epicId/edit',
  path: '/app/epics/$epicId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/epics/$epicId/edit': {
      id: '/app/epics/$epicId/edit'
      path: '/app/epics/$epicId/edit'
      fullPath: '/app/epics/$epicId/edit'
      preLoaderRoute: typeof AppEpicsEpicIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/app/epics/$epicId/edit': typeof AppEpicsEpicIdEditRoute
}

export interface FileRoutesByTo {
  '/app/epics/$epicId/edit': typeof AppEpicsEpicIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app/epics/$epicId/edit': typeof AppEpicsEpicIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app/epics/$epicId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/app/epics/$epicId/edit'
  id: '__root__' | '/app/epics/$epicId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppEpicsEpicIdEditRoute: typeof AppEpicsEpicIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppEpicsEpicIdEditRoute: AppEpicsEpicIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app/epics/$epicId/edit"
      ]
    },
    "/app/epics/$epicId/edit": {
      "filePath": "app/epics/$epicId/edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
